site_name: Estructuras Complejas Otoño 2023
site_description: Curso en Línea de la Facultad de Arquitectura de la Universidad Anáhuac México
site_author: Rodrigo Shiordia López
copyright: Copyright 2023 Rodrigo Shiordia - Creative Commons Attribution Non Commercial

site_url: https://rshiordia.github.io/curso-complejas/

theme:
  name: material

markdown_extensions:
  - attr_list
  - footnotes
  - toc:
      title: Contenido
